format ='\[$username@$hostname\]$character'
right_format = '$all'
add_newline = false

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
home_symbol = '/home/hak53q' # 我不會弄...
read_only = ' 唯讀'
read_only_style = 'red bold'
truncation_length = 2
fish_style_pwd_dir_length = 2

[username]
format = '[$user]($style)'
style_root = 'red bold'
style_user = 'none'
disabled = false
show_always = true

[hostname]
format = '[$hostname]($style)'
style = 'none'
ssh_only = false
disabled = false

[character]
disabled = false
success_symbol = '\$'
error_symbol = '[\$](red bold)'

[cmd_duration]
min_time = 1000

[git_branch]
symbol = "git "

[package]
symbol = 'pkg '

[docker_context]
symbol = 'docker '

[c]
symbol = 'c '

[cpp]
symbol = 'c++ '

[cmake]
symbol = 'cmake '

[golang]
symbol = 'go '

[java]
symbol = 'java '

[kotlin]
symbol = 'kt '

[lua]
symbol = 'lua '

[meson]
symbol = 'meson '

[nix_shell]
symbol = 'nix '

[nodejs]
symbol = 'nodejs '

[perl]
symbol = 'perl '

[python]
symbol = 'py '

[rust]
symbol = 'rs '

[zig]
symbol = 'zig '
